on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check --impure
        env:
          NIXPKGS_ALLOW_BROKEN: 1

      # Verify the update script WORKS but we don't actually commit anything
      # in the test job.
      - run: ./update
