name: update-sources
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - run: nix flake update
      - run: ./update
      - name: Setup Git user
        run: |
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
      - name: Commit changes
        run: |
          git add -A
          git commit -m 'update sources.json' | true
          git push -u origin main
